# Generated by Django 5.1.5 on 2025-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokalizacja', models.CharField(max_length=255)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('powierzchnia_calkowita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liczba_pokoi', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
