# Generated by Django 5.1.5 on 2025-01-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktualne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.FloatField(blank=True, db_column='Cena', null=True)),
                ('cena_za_m2', models.FloatField(blank=True, db_column='Cena_za_m2', null=True)),
                ('lokalizacja', models.TextField(blank=True, db_column='Lokalizacja', null=True)),
                ('powierzchnia_calkowita', models.FloatField(blank=True, db_column='Powierzchnia_calkowita', null=True)),
                ('liczba_pokoi', models.IntegerField(blank=True, db_column='Liczba_pokoi', null=True)),
                ('piętro', models.TextField(blank=True, db_column='Piętro', null=True)),
                ('typ_budynku', models.TextField(blank=True, db_column='Typ_budynku', null=True)),
                ('rok_budowy', models.TextField(blank=True, db_column='Rok_budowy', null=True)),
                ('typ_ogloszeniodawcy', models.TextField(blank=True, db_column='Typ_ogloszeniodawcy', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('forma_wlasności', models.TextField(blank=True, db_column='Forma_wlasności', null=True)),
                ('dostępne_od', models.TextField(blank=True, db_column='Dostępne_od', null=True)),
                ('stan_wykończenia', models.TextField(blank=True, db_column='Stan_wykończenia', null=True)),
                ('rynek', models.TextField(blank=True, db_column='Rynek', null=True)),
                ('winda', models.IntegerField(blank=True, db_column='Winda', null=True)),
                ('ogrzewanie', models.IntegerField(blank=True, db_column='Ogrzewanie', null=True)),
                ('województwo', models.TextField(blank=True, db_column='Województwo', null=True)),
                ('miasto', models.TextField(blank=True, db_column='Miasto', null=True)),
                ('dzielnica', models.TextField(blank=True, db_column='Dzielnica', null=True)),
                ('ulica', models.TextField(blank=True, db_column='Ulica', null=True)),
                ('liczba_pięter', models.TextField(blank=True, db_column='Liczba_pięter', null=True)),
                ('balkon', models.IntegerField(blank=True, db_column='Balkon', null=True)),
                ('piwnica', models.IntegerField(blank=True, db_column='Piwnica', null=True)),
                ('garaz', models.IntegerField(blank=True, db_column='Garaz', null=True)),
                ('miejsce_parkingowe', models.IntegerField(blank=True, db_column='Miejsce_parkingowe', null=True)),
                ('ogrzewanie_rodzaj', models.TextField(blank=True, db_column='Ogrzewanie_rodzaj', null=True)),
                ('ochrona', models.IntegerField(blank=True, db_column='Ochrona', null=True)),
                ('ogloszeniodawca', models.TextField(blank=True, db_column='Ogłoszeniodawca', null=True)),
                ('dzielnica_num', models.IntegerField(blank=True, db_column='Dzielnica_num', null=True)),
            ],
            options={
                'db_table': 'aktualne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archiwalne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.TextField(blank=True, db_column='Cena', null=True)),
                ('cena_za_m2', models.TextField(blank=True, db_column='Cena_za_m2', null=True)),
                ('lokalizacja', models.TextField(blank=True, db_column='Lokalizacja', null=True)),
                ('powierzchnia_calkowita', models.TextField(blank=True, db_column='Powierzchnia_calkowita', null=True)),
                ('liczba_pokoi', models.IntegerField(blank=True, db_column='Liczba_pokoi', null=True)),
                ('piętro', models.TextField(blank=True, db_column='Piętro', null=True)),
                ('typ_budynku', models.TextField(blank=True, db_column='Typ_budynku', null=True)),
                ('rok_budowy', models.TextField(blank=True, db_column='Rok_budowy', null=True)),
                ('typ_ogloszeniodawcy', models.TextField(blank=True, db_column='Typ_ogloszeniodawcy', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('forma_wlasnosci', models.TextField(blank=True, db_column='Forma_wlasnosci', null=True)),
                ('dostępne_od', models.TextField(blank=True, db_column='Dostepne_od', null=True)),
                ('stan_wykonczenia', models.TextField(blank=True, db_column='Stan_wykonczenia', null=True)),
                ('rynek', models.TextField(blank=True, db_column='Rynek', null=True)),
                ('winda', models.IntegerField(blank=True, db_column='Winda', null=True)),
                ('ogrzewanie', models.IntegerField(blank=True, db_column='Ogrzewanie', null=True)),
                ('województwo', models.TextField(blank=True, db_column='Wojewodztwo', null=True)),
                ('miasto', models.TextField(blank=True, db_column='Miasto', null=True)),
                ('dzielnica', models.TextField(blank=True, db_column='Dzielnica', null=True)),
                ('ulica', models.TextField(blank=True, db_column='Ulica', null=True)),
                ('liczba_pieter', models.TextField(blank=True, db_column='Liczba_pieter', null=True)),
                ('balkon', models.IntegerField(blank=True, db_column='Balkon', null=True)),
                ('piwnica', models.IntegerField(blank=True, db_column='Piwnica', null=True)),
                ('garaz', models.IntegerField(blank=True, db_column='Garaz', null=True)),
                ('miejsce_parkingowe', models.IntegerField(blank=True, db_column='Miejsce_parkingowe', null=True)),
                ('ogrzewanie_rodzaj', models.TextField(blank=True, db_column='Ogrzewanie_rodzaj', null=True)),
                ('ochrona', models.IntegerField(blank=True, db_column='Ochrona', null=True)),
                ('ogloszeniodawca', models.TextField(blank=True, db_column='Ogłoszeniodawca', null=True)),
                ('dzielnica_num', models.IntegerField(blank=True, db_column='Dzielnica_num', null=True)),
                ('data', models.TextField(blank=True, db_column='Data', null=True)),
            ],
            options={
                'db_table': 'archiwalne',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
